# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17YVO3Xn7E6uGgB3u2317xnVdSUZ6LgVr
"""

class Motor:
    def __init__(self, nombre, tipo_motor : str, potencia_motor: int, peso : float):
        self.nombre_ = nombre
        self.tipo_motor_ = tipo_motor
        self.potencia_motor_ = potencia_motor
        self.peso_ = peso

class Vehiculo:

    def __init__(self, chasis : str, modelo: str, year : int, motor) :
        self.chasis_ = chasis
        self.modelo_ = modelo
        self.year_= year
        self.consumo_de_gas_ = None
        self.motor_ = motor
        global valor_chasis_
        while chasis is "A" or "B" :
          if chasis == "A" :
            valor_chasis_ = 0.5
          elif chasis == "B":
            valor_chasis_ = 0.3
          else :
            print("ingrese un valor correcto")
          break


    def consumo_de_gas_ (self):
        consumo_de_gasolina_ = ((1.1 * (self.motor.potencia_motor if self.motor.potencia_motor >0 else 0)) + (0.2 * (self.motor.peso if self.peso >0 else 0)) - (valor_chasis_))
        self.consumo_de_gas_ = consumo_de_gasolina_
        print(f"Consumo de gasolina del vehículo {self.modelo_}: {self.consumo_de_gas_:.2f} litros/km")


class Carrito(Vehiculo):
    def __init__(self, chasis, modelo, year, motor):
        super().__init__(chasis, modelo, year, motor)
    def __str__(self):
        return f"Carrito - Modelo: {self.modelo_}, Año: {self.year_},chasis: {self.chasis_}"

class Tractor(Vehiculo):
    def __init__(self, chasis, modelo, year, motor):
        super().__init__(chasis, modelo, year, motor)
        return f"Tractor - Modelo: {self.modelo_}, Año: {self.year_},chasis: {self.chasis_}"

class Camion(Vehiculo):
    def __init__(self, chasis, modelo, year, motor):
        super().__init__(chasis, modelo, year, motor)
        return f"Camión - Modelo: {self.modelo_}, Año: {self.year_},chasis: {self.chasis_}"

class Yate(Vehiculo):
    def __init__(self, chasis, modelo, year, motor):
        super().__init__(chasis, modelo, year, motor)
        return f"Yate - Modelo: {self.modelo_}, Año: {self.year_},chasis: {self.chasis_}"

class Moto(Vehiculo):
    def __init__(self, chasis, modelo, year, motor):
        super().__init__(chasis, modelo, year, motor)
        return f"Moto - Modelo: {self.modelo_}, Año: {self.year_},chasis: {self.chasis_}"

global vehiculos
vehiculos = []


def crear_vehiculo_(vehiculo):
  print("Ingrese el nombre del motor")
  nombre = input()
  print("Ingrese que tipo de motor es")
  tipo_motor = input()
  print("Ingrese la potencia del motor")
  potencia_motor = int(input())
  print("Ingrese el peso del motor")
  peso_ = float(input())
  motor_nuevo_ = Motor(nombre, tipo_motor, potencia_motor, peso_)
  print("Ingrese el modelo del vehiculo")
  modelo = input()
  print("Ingrese el año del modelo del vehiculo")
  year = int(input())
  print("Ingrese el chasis que va a tener su vehiculo(Elija entre chasis A o B)")
  chasis = input()
  print("Él consumo de gasolina seria el siguiente:")


  if vehiculo == "Carrito":
    vehiculos.append(Carrito(chasis, modelo, year, motor_nuevo_))
  elif vehiculo == "Tractor":
    vehiculos.append(Tractor(chasis, modelo, year, motor_nuevo_))
  elif vehiculo == "Camión":
    vehiculos.append(Camion(chasis, modelo, year, motor_nuevo_))
  elif vehiculo == "Yate":
    vehiculos.append(Yate(chasis, modelo, year, motor_nuevo_))
  elif vehiculo == "Moto":
    vehiculos.append(Moto(chasis, modelo, year, motor_nuevo_))
def menu():

  while True:
    print("1. Crear un carro\n2. Crear un tractor\n3. Crear un camión\n4. Crear un yate\n5. Crear una moto\n6. Todos los vehículos\n7. Salir\n")

    x = int(input("Seleccione una opción: "))
    if x == 1:
        crear_vehiculo_("Carrito")
    elif x == 2:
        crear_vehiculo_("Tractor")
    elif x == 3:
        crear_vehiculo_("Camión")
    elif x == 4:
        crear_vehiculo_("Yate")
    elif x == 5:
        crear_vehiculo_("Moto")
    elif x == 6:
        for n in vehiculos:
          print(n)
    elif x == 7:
        print("Saliendo del programa.")
        break
    else:
        print("Opción no válida. Por favor, seleccione una opción válida.")




menu()